// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/11/2025, 7:04:29 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/yuktrix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/plugins/**/*.{js,ts,mjs}","D:/yuktrix/composables/**/*.{js,ts,mjs}","D:/yuktrix/utils/**/*.{js,ts,mjs}","D:/yuktrix/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/yuktrix/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;